version: '2'
services:
  rasatalk:
    build:
      context: .
      dockerfile: ./internals/docker/Dockerfile
    depends_on:
      - rasa
      - mongodb
    command: npm run start:prod
    networks:
      - my-net
    environment:
      - MONGOCONNECTIONSTRING=mongodb://mongo:27017/rasa-talk
      - RASASERVER=http://rasa:5000
      - DEBUG=*,-babel
      - PORT=80
    ports:
      - 80:80
      - 443:443
  rasa:
    container_name: "rasa"
    image: rasa/rasa_nlu
    restart: always
    networks:
      - my-net
    ports:
    - 5000:5000
    volumes:
      - ./data/rasa/projects:/app/projects
      - ./data/rasa/logs:/app/logs
      - ./data/rasa/data:/app/data
  mongodb:
    container_name: "mongo"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - my-net
    volumes:
      - ./data/mongo:/data/db
networks:
  my-net:
    driver: bridge
